### ISSUE TITLE
F20-6pm-d Course Info Epic

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-f20/proj-ucsb-cs-las#11]
Theme of this epic is information related to courses.

* Change course name to course number
* Add sorting to courses table
* Courses table on main page should only show info for current quarter.
* Add validation to course add / edit features.
* Add CSV download for course information (on Admin's page for maintaining courses.)
* Add CSV upload for course information (on Admin's page for maintaining courses.)
* Add admin ability to list all tutors that have ever served as an LA for a given course number.

**Comment by jayleenli** [comment]
- [x] Change course name to course number
- [x] Add sorting to courses table
- [ ] Courses table on main page should only show info for current quarter.
- [ ] Add validation to course add / edit features. (seems to be kinda not working, and doesn't give good validation feedback
- [ ] Add CSV download for course information (on Admin's page for maintaining courses.)
- [ ] Add CSV upload for course information (on Admin's page for maintaining courses.)
- [ ] Add admin ability to list all tutors that have ever served as an LA for a given course number.
